# This file is a mashup of several sources, including:
# - https://patriksvensson.se/posts/2020/03/creating-release-artifacts-with-github-actions
# - https://github.com/vrchat-community/template-package/blob/main/.github/workflows/release.yml
# - and some improv

name: .NET

on:
  workflow_dispatch:

env:
  outputAppFolder: "XYVR"
  netCsProjWindows: "ui-webview-windows/ui-webview-windows.csproj"
  netCsProjLinux: "ui-photino-linux/ui-photino-linux.csproj"
  packageName: "dev.hai-vr.xyvr"
  applicationNameWindows: "XYVR"
  applicationNameLinux: "xyvr"

permissions:
  contents: write

jobs:
  build_windows:
    name: Build Windows Executable
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.prop }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
          path: "Packages/${{env.packageName}}/package.json"
          prop_path: "version"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build React app
        run: |
          cd ui-frontend/src
          npm install
          npm run build-and-copy

      - name: Build
        shell: bash
        run: |
          dotnet publish ${{env.netCsProjWindows}} \
            --runtime win-x64 \
            --self-contained true \
            -c Release \
            -o "App/${{env.outputAppFolder}}"

      - name: Create Executable Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "App/"
          filename: "../${{ env.applicationNameWindows }}-${{ steps.version.outputs.prop }}-windows-x64-executable.zip"

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: "${{ env.applicationNameWindows }}-${{ steps.version.outputs.prop }}-windows-x64-executable.zip"

  build_linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.prop }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
          path: "Packages/${{env.packageName}}/package.json"
          prop_path: "version"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build React app
        run: |
          cd ui-frontend/src
          npm install
          npm run build-and-copy

      - name: Build
        run: |
          dotnet publish ${{env.netCsProjLinux}} \
            --runtime linux-x64 \
            --self-contained true \
            -c Release \
            -o "App/${{env.outputAppFolder}}"

      - name: Create Executable Tarball
        run: |
          cd App
          tar -czf ../${{ env.applicationNameLinux }}-${{ steps.version.outputs.prop }}-linux-x64-executable.tar.gz .

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: "${{ env.applicationNameLinux }}-${{ steps.version.outputs.prop }}-linux-x64-executable.tar.gz"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ needs.build_windows.outputs.version }}
          files: |
            windows-executable/${{ env.applicationNameWindows }}-${{ needs.build_windows.outputs.version }}-windows-x64-executable.zip
            linux-executable/${{ env.applicationNameLinux }}-${{ needs.build_linux.outputs.version }}-linux-x64-executable.tar.gz
